--- #YAML:1.0
name:               WordPress-XMLRPC
version:            1.23
abstract:           api to wordpress xml rpc calls
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LEOCHARRE::CLI2:   0
    LEOCHARRE::Debug:  0
    Smart::Comments:   0
    SOAP::Lite:        0
    XMLRPC::Lite:      0
    YAML:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
