--- #YAML:1.0
name:               XML-RPC
version:            0.9
abstract:           Pure Perl implementation for an XML-RPC client and server
author:
    - Niek Albers
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
    Test::More:      0.17
    XML::TreePP:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
